[tools]
android-sdk = "latest"
"github:Genymobile/scrcpy" = "4.0"
"github:cesarferreira/byedroid" = "0.9.0"
gradle = "9.6.0"
java = "26.0.1"

[env]
_.path = {tools = true, path = [
 "${ANDROID_HOME}/platform-tools",
 "${ANDROID_HOME}/build-tools/35.0.0",
]}

[settings]
env_shell_expand = true
ruby.compile = false

[tasks.install-android-sdk]
sources = ["android-sdk-packages.txt"]
run = """
  export TMPDIR="${PWD}/.mise/tmp"
  mkdir -p ${TMPDIR} ${ANDROID_HOME}
  yes | sdkmanager --licenses
  sdkmanager --package_file=android-sdk-packages.txt
  yes | sdkmanager --licenses
  rm -rf ${TMPDIR}
"""

[tasks.build]
depends = ["install-android-sdk"]
sources = [
'build.gradle.kts',
'gradle.properties',
'src/**',
'settings.gradle.kts',
'android-sdk-packages.txt'
]
run = "gradle assembleDebug"
alias = "apk"

[tasks.deps]
run = "bundle install"
alias = "d"

[tasks.build-release-apk]
depends = ["install-android-sdk", "deps"]
sources = [
'Gemfile',
'Gemfile.lock',
'fastlane/Fastfile',
'build.gradle.kts',
'gradle.properties',
'src/**',
'settings.gradle.kts',
'android-sdk-packages.txt'
]
run = "bundle exec fastlane android build_apk"
alias = "fastlane-apk"

[tasks.metadata]
sources = ['fastlane/metadata/android/en-US/*']
run = "fastlane android metadata"
alias = "m"

[tasks.build-release-aab]
depends = ["install-android-sdk", "deps"]
sources = [
'Gemfile',
'Gemfile.lock',
'fastlane/Fastfile',
'build.gradle.kts',
'gradle.properties',
'src/**',
'settings.gradle.kts',
'android-sdk-packages.txt'
]
run = "bundle exec fastlane android build_aab"
alias = "fastlane-aab"


