[tools]
android-sdk = "latest"
gradle = "latest"
java = "latest"

[env]
_.path = {tools = true, path = ["${ANDROID_HOME}/platform-tools"]}

[settings]
env_shell_expand = true


[tasks.install-android-sdk]
sources = ["android-sdk-packages.txt"]
run = """
  export TMPDIR="${PWD}/.mise/tmp"
  mkdir -p ${TMPDIR} ${ANDROID_HOME}
  yes | sdkmanager --licenses
  sdkmanager --package_file=android-sdk-packages.txt
  yes | sdkmanager --licenses
  rm -rf ${TMPDIR}
"""

[tasks.build]
depends = ["install-android-sdk"]
sources = [
'build.gradle.kts',
'gradle.properties',
'src/**',
'settings.gradle.kts',
'android-sdk-packages.txt'
]
run = "gradle assembleDebug"
alias = "b"
